name: Build RPM Package

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-image .

    - name: Run container and inspect repository configuration
      run: |
        docker run --rm -v $(pwd)/repo_configs:/repo_configs my-image cp /etc/yum.repos.d/*.repo /repo_configs
      # Optionally, you can use 'docker cp' to copy the files from a running container to the host machine

    - name: Build RPM package
      run: |
        docker run --rm -v ${{ github.workspace }}:/opt -w /opt rpm-builder

    - name: Upload RPM artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-python-app
        path: ${{ github.workspace }}/rpmbuild/RPMS/x86_64/*.rpm
